-- =============================================================================
-- Easel — Initial Schema
-- Principal Engineer: Database Design v1.0
--
-- Architecture decisions:
--   1. All tables in the public schema; auth.users is managed by Supabase Auth.
--   2. Row Level Security (RLS) is ENABLED on every table — data isolation is
--      enforced at the DB layer, not just in application code.
--   3. Partners (GF + BF) are linked through the `couples` table. Helper
--      functions resolve couple membership for RLS policies without N+1 queries.
--   4. Timestamps use TIMESTAMPTZ (not TIMESTAMP) so they store UTC and convert
--      correctly to any client timezone.
--   5. Cycle dates use DATE (not TIMESTAMPTZ) because a period start date has
--      no meaningful time component and timezone conversion would corrupt it.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. profiles
--    One row per auth user. Created automatically via trigger on signup.
--    Extends auth.users with app-specific fields (role, display_name).
-- ---------------------------------------------------------------------------
CREATE TABLE public.profiles (
  id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email         TEXT NOT NULL,
  role          TEXT CHECK (role IN ('girlfriend', 'boyfriend')),
  display_name  TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.profiles IS
  'App-level user profile. Mirrors auth.users.id as PK — one row per user.';
COMMENT ON COLUMN public.profiles.role IS
  'Set during onboarding. NULL until onboarding is complete.';

-- Auto-create a profile row when a new auth user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Auto-update updated_at on any profile change
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ---------------------------------------------------------------------------
-- 2. couples
--    One row per girlfriend–boyfriend pair.
--    GF creates the row and generates a link_code. BF uses the code to join.
--    Only one active couple per user is enforced at the application layer.
-- ---------------------------------------------------------------------------
CREATE TABLE public.couples (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  girlfriend_id         UUID NOT NULL REFERENCES public.profiles(id),
  boyfriend_id          UUID REFERENCES public.profiles(id),
  link_code             TEXT UNIQUE,
  link_code_expires_at  TIMESTAMPTZ,
  status                TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'linked')),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  linked_at             TIMESTAMPTZ,

  -- A user can only be in one active couple at a time
  CONSTRAINT unique_girlfriend UNIQUE (girlfriend_id),
  CONSTRAINT no_self_link CHECK (girlfriend_id <> boyfriend_id)
);

COMMENT ON TABLE public.couples IS
  'Links a girlfriend and boyfriend. GF creates the row; BF links via code.';
COMMENT ON COLUMN public.couples.link_code IS
  '6-digit numeric code generated by GF. Expires after 24 hours.';

CREATE TRIGGER couples_updated_at
  BEFORE UPDATE ON public.couples
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ---------------------------------------------------------------------------
-- 3. cycle_settings
--    One row per GF user (1:1). Stores the rolling cycle parameters used by
--    all phase calculations. Updated any time GF edits Settings.
-- ---------------------------------------------------------------------------
CREATE TABLE public.cycle_settings (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 UUID UNIQUE NOT NULL REFERENCES public.profiles(id),
  avg_cycle_length        SMALLINT NOT NULL DEFAULT 28
                            CHECK (avg_cycle_length BETWEEN 21 AND 45),
  avg_period_length       SMALLINT NOT NULL DEFAULT 5
                            CHECK (avg_period_length BETWEEN 2 AND 10),
  last_period_start_date  DATE NOT NULL,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.cycle_settings IS
  'Girlfriend''s rolling cycle parameters. 1:1 with profiles via UNIQUE user_id.';

CREATE TRIGGER cycle_settings_updated_at
  BEFORE UPDATE ON public.cycle_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ---------------------------------------------------------------------------
-- 4. period_logs
--    Historical period entries. Enables the app to refine predictions over
--    time and provide an AI-powered cycle summary in the future.
-- ---------------------------------------------------------------------------
CREATE TABLE public.period_logs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.profiles(id),
  start_date  DATE NOT NULL,
  end_date    DATE,
  notes       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT end_after_start CHECK (end_date IS NULL OR end_date >= start_date),
  UNIQUE (user_id, start_date)
);

COMMENT ON TABLE public.period_logs IS
  'One row per period. end_date can be filled in later when the period ends.';


-- ---------------------------------------------------------------------------
-- 5. daily_logs
--    Daily mood, energy, and symptom check-in. One row per user per date.
--    The mood/energy 1–5 scale maps to emoji in the UI.
-- ---------------------------------------------------------------------------
CREATE TABLE public.daily_logs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.profiles(id),
  log_date    DATE NOT NULL,
  mood        SMALLINT CHECK (mood BETWEEN 1 AND 5),
  energy      SMALLINT CHECK (energy BETWEEN 1 AND 5),
  symptoms    TEXT[],   -- e.g. ['cramps', 'bloating', 'headache']
  notes       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (user_id, log_date)
);

COMMENT ON TABLE public.daily_logs IS
  'Daily check-in. symptoms is a free-form text array for flexible tagging.';

CREATE TRIGGER daily_logs_updated_at
  BEFORE UPDATE ON public.daily_logs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ---------------------------------------------------------------------------
-- 6. sos_signals
--    GF sends an SOS; BF acknowledges it. Realtime subscription on this table
--    delivers instant notification to BF's device without polling.
-- ---------------------------------------------------------------------------
CREATE TABLE public.sos_signals (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  couple_id       UUID NOT NULL REFERENCES public.couples(id),
  sender_id       UUID NOT NULL REFERENCES public.profiles(id),
  type            TEXT NOT NULL
                    CHECK (type IN ('sweet_tooth', 'need_a_hug', 'cramps_alert', 'quiet_time')),
  message         TEXT,
  acknowledged_at TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.sos_signals IS
  'GF-to-BF SOS events. Realtime subscription drives the in-app alert on BF side.';
COMMENT ON COLUMN public.sos_signals.acknowledged_at IS
  'Set by BF when they tap "Got it". NULL = unacknowledged.';


-- ---------------------------------------------------------------------------
-- 7. push_tokens
--    Expo push notification tokens. One per device per user.
--    Used to send background notifications (e.g. SOS while app is closed).
-- ---------------------------------------------------------------------------
CREATE TABLE public.push_tokens (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.profiles(id),
  token       TEXT NOT NULL,
  platform    TEXT NOT NULL CHECK (platform IN ('ios', 'android', 'web')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (user_id, token)
);

COMMENT ON TABLE public.push_tokens IS
  'Expo push tokens for background SOS notifications. One row per device.';

CREATE TRIGGER push_tokens_updated_at
  BEFORE UPDATE ON public.push_tokens
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ---------------------------------------------------------------------------
-- 8. user_preferences
--    Per-user app configuration: notification toggles, AI settings,
--    and the Vercel proxy URL (set once after deployment).
--    API keys themselves are NEVER stored here — they live in Vercel env vars.
-- ---------------------------------------------------------------------------
CREATE TABLE public.user_preferences (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                   UUID UNIQUE NOT NULL REFERENCES public.profiles(id),
  notifications_enabled     BOOLEAN NOT NULL DEFAULT TRUE,
  sos_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ai_greetings_enabled      BOOLEAN NOT NULL DEFAULT TRUE,
  proxy_url                 TEXT,   -- Vercel proxy URL (non-secret)
  ai_model                  TEXT DEFAULT 'MiniMax-M2.5',
  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.user_preferences IS
  'Per-user app config. proxy_url is the only AI-related value stored here.
   Actual API keys (MINIMAX_API_KEY, CLIENT_TOKEN) live in Vercel env vars.';

CREATE TRIGGER user_preferences_updated_at
  BEFORE UPDATE ON public.user_preferences
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- =============================================================================
-- HELPER FUNCTIONS FOR RLS
-- SECURITY DEFINER = runs as the function owner (postgres), not the caller.
-- This lets RLS policies safely join across tables without infinite recursion.
-- =============================================================================

-- Returns the couple_id for the authenticated user, or NULL if not linked.
CREATE OR REPLACE FUNCTION public.my_couple_id()
RETURNS UUID AS $$
  SELECT id
  FROM public.couples
  WHERE (girlfriend_id = auth.uid() OR boyfriend_id = auth.uid())
    AND status = 'linked'
  LIMIT 1;
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- Returns the partner's user ID for the authenticated user, or NULL.
CREATE OR REPLACE FUNCTION public.my_partner_id()
RETURNS UUID AS $$
  SELECT CASE
    WHEN girlfriend_id = auth.uid() THEN boyfriend_id
    ELSE girlfriend_id
  END
  FROM public.couples
  WHERE (girlfriend_id = auth.uid() OR boyfriend_id = auth.uid())
    AND status = 'linked'
  LIMIT 1;
$$ LANGUAGE sql SECURITY DEFINER STABLE;


-- =============================================================================
-- ROW LEVEL SECURITY
-- Every table is locked down. Users can only see what they're allowed to see.
-- =============================================================================

-- profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profiles: read own and partner"
  ON public.profiles FOR SELECT
  USING (id = auth.uid() OR id = public.my_partner_id());

CREATE POLICY "profiles: update own only"
  ON public.profiles FOR UPDATE
  USING (id = auth.uid());


-- couples
ALTER TABLE public.couples ENABLE ROW LEVEL SECURITY;

CREATE POLICY "couples: read own couple"
  ON public.couples FOR SELECT
  USING (girlfriend_id = auth.uid() OR boyfriend_id = auth.uid());

CREATE POLICY "couples: GF can insert"
  ON public.couples FOR INSERT
  WITH CHECK (girlfriend_id = auth.uid());

CREATE POLICY "couples: BF can link (update boyfriend_id)"
  ON public.couples FOR UPDATE
  USING (
    -- BF can update to add themselves; GF can update their own row
    id = public.my_couple_id()
    OR girlfriend_id = auth.uid()
  );


-- cycle_settings
ALTER TABLE public.cycle_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "cycle_settings: read own or partner's"
  ON public.cycle_settings FOR SELECT
  USING (user_id = auth.uid() OR user_id = public.my_partner_id());

CREATE POLICY "cycle_settings: write own only"
  ON public.cycle_settings FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- period_logs
ALTER TABLE public.period_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "period_logs: read own or partner's"
  ON public.period_logs FOR SELECT
  USING (user_id = auth.uid() OR user_id = public.my_partner_id());

CREATE POLICY "period_logs: write own only"
  ON public.period_logs FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- daily_logs
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "daily_logs: read own or partner's"
  ON public.daily_logs FOR SELECT
  USING (user_id = auth.uid() OR user_id = public.my_partner_id());

CREATE POLICY "daily_logs: write own only"
  ON public.daily_logs FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- sos_signals
ALTER TABLE public.sos_signals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "sos_signals: couple members can read"
  ON public.sos_signals FOR SELECT
  USING (couple_id = public.my_couple_id());

CREATE POLICY "sos_signals: sender can insert"
  ON public.sos_signals FOR INSERT
  WITH CHECK (
    couple_id = public.my_couple_id()
    AND sender_id = auth.uid()
  );

CREATE POLICY "sos_signals: recipient can acknowledge (update)"
  ON public.sos_signals FOR UPDATE
  -- Only the non-sender partner can flip acknowledged_at
  USING (
    couple_id = public.my_couple_id()
    AND sender_id <> auth.uid()
  );


-- push_tokens
ALTER TABLE public.push_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "push_tokens: own only"
  ON public.push_tokens FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- user_preferences
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "user_preferences: own only"
  ON public.user_preferences FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- =============================================================================
-- REALTIME
-- Enable Realtime publication for tables that need live sync.
-- sos_signals: BF receives instant alert when GF sends SOS.
-- =============================================================================

-- The default Supabase publication. Add tables that need Realtime.
ALTER PUBLICATION supabase_realtime ADD TABLE public.sos_signals;
ALTER PUBLICATION supabase_realtime ADD TABLE public.cycle_settings;
